Add fluent API and Initial migration
BinaryStudioAcademy/bsa-winter21-22-recodo pull request #13
Opened 2022-02-09 14:26 UTC by VitalikMatvieiev

2022-02-09 16:03 UTC, Jyuart requested changes

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.API/Startup.cs
> +            };
```suggestion
            using var scope = app.ApplicationServices.GetRequiredService<IServiceScopeFactory>().CreateScope();
            using var context = scope.ServiceProvider.GetRequiredService<RecodoDbContext>();
            context.Database.Migrate();
```
You can use 'using' declaration in both cases. The same for GetRequiredService

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/CommentReactionConfiguration.cs
> +    public class CommentReactionConfiguration : IEntityTypeConfiguration<CommentReaction>
I think you can configure these as owned entities.
https://docs.microsoft.com/en-us/ef/core/modeling/owned-entities
Cause comment reactions are strictly dependents on the comments

Just put a collection of CommentReactions in the Comment entity and then configure in the CommentConfiguration with builder.OwnsMany()

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/CommentReactionConfiguration.cs
> +            builder.HasOne(p=>p.User).WithMany().HasForeignKey(p=>p.UserId);
```suggestion
            builder.HasOne(p => p.User).WithMany().HasForeignKey(p=>p.UserId);
```
Cleanliness. Here and everywhere else

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/CommentReactionConfiguration.cs
> +    public class CommentReactionConfiguration : IEntityTypeConfiguration<CommentReaction>
We can even make Comment as an owned entity of the video, but let's not make it like this for now.

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/NotificationConfiguration.cs
> +        public void Configure(EntityTypeBuilder<Notification> builder)
Type, CreatedAt and IsRead?

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/NotificationConfiguration.cs
> +            builder.Property(p => p.Massage).IsRequired();
```suggestion
            builder.Property(p => p.Message).IsRequired();
```

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/TeamInvitationConfiguration.cs
> +    public class TeamInvitationConfiguration : IEntityTypeConfiguration<TeamInvitation>
You can delete this entity and configuration completely. EF Core 5.0 is smart enough to create a join table it automatically

2022-02-09 16:03 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/VideoReactionConfiguration.cs
> +    public class VideoReactionConfiguration : IEntityTypeConfiguration<VideoReaction>
Also make it owned entity in relation to the video

2022-02-09 16:38 UTC, VitalikMatvieiev commented on backend/Recodo.DAL/Entities/Configuration/TeamInvitationConfiguration.cs
> +    public class TeamInvitationConfiguration : IEntityTypeConfiguration<TeamInvitation>
But we need more fields than ids in case where EF Core 5.0

2022-02-09 17:18 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Configuration/TeamInvitationConfiguration.cs
> +    public class TeamInvitationConfiguration : IEntityTypeConfiguration<TeamInvitation>
Aah, yes, you're right!
Then just don't create an id for this entity. We can make it a composite one

2022-02-10 08:07 UTC, VitalikMatvieiev commented on backend/Recodo.DAL/Entities/Configuration/CommentReactionConfiguration.cs
> +    public class CommentReactionConfiguration : IEntityTypeConfiguration<CommentReaction>
But if I understand clearly, we should have property with Type Comment, and in this case we can use 'Owns'

2022-02-10 09:21 UTC, Jyuart approved these changes

2022-02-10 09:23 UTC, Anatolii-Ivanov approved these changes

2022-02-10 09:24 UTC, merged