Feature 33 countdown form
BinaryStudioAcademy/bsa-winter21-22-recodo pull request #21
Opened 2022-02-14 05:00 UTC by shmato4ek

2022-02-14 10:13 UTC, Anatolii-Ivanov requested changes
Why do you have all that files? StickPanel, Icons, fonts...

2022-02-14 10:13 UTC, Anatolii-Ivanov commented on RecodoDesktop/RecodoDesktop/App.xaml.cs
> +        }
I don't think you need it now

2022-02-14 10:13 UTC, Anatolii-Ivanov commented on RecodoDesktop/RecodoDesktop/Countdown.xaml.cs
> +}
check tabs

2022-02-14 10:13 UTC, Anatolii-Ivanov commented on RecodoDesktop/RecodoDesktop/Countdown.xaml.cs
> +}
Add an ability to add constructor parameter function, which will be executed after countdown is finished

2022-02-14 10:13 UTC, Anatolii-Ivanov commented on RecodoDesktop/RecodoDesktop/Countdown.xaml.cs
> +}
Move it to a function, minimum logic in a constructor

2022-02-15 10:04 UTC, Jyuart requested changes
Good start, but please update it with following features:
- It should be displayed full screen (with background blurred or something like this, so that the user do not miss the moment recording starts)
- Remove that red circle. It's too acid
- And the window control should not be visible (not the debug buttons)

2022-02-16 13:17 UTC, Anatolii-Ivanov approved these changes

2022-02-16 16:37 UTC, Jyuart approved these changes

2022-02-16 16:37 UTC, merged