Feature 57 comments and reactions
BinaryStudioAcademy/bsa-winter21-22-recodo pull request #44
Opened 2022-02-22 17:48 UTC by shmato4ek

2022-03-24 09:11 UTC, Anatolii-Ivanov reviewed
And this file again
frontend/src/assets/himn.mp4

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on backend/Recodo.BLL/Services/CommentService.cs
> +            var commentEntity = await _context.Comments.FirstOrDefaultAsync(p => p.Id == commentId);
It's better to check owner (user) everywhere, as theoretically any user can change any comment by id via postmen

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on backend/Recodo.BLL/Services/ReactionsService.cs
> +                if (reaction.Reaction == video.Reactions.FirstOrDefault().Reaction)
If more than 1 reaction is presented?

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on backend/Recodo.BLL/Services/ReactionsService.cs
> +            var reactions = _context.CommentReactions.Where(x => x.UserId == reaction.UserId && x.CommentId == reaction.CommentId);
Where -> FirstOrDefault

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on backend/Recodo.DAL/Migrations/20220317133458_AddVideoToComments.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Empty migration?

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on frontend/src/app/app-routing.module.ts
> +    // canActivate : [TokenExistsGuard]
Don't forget to get back

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on frontend/src/app/modules/workspace/video/comment-reactions/comment-reactions.component.ts
> +  public GetReactions(reactionNumber: number) {
You can get by type and assign this type on loading data

2022-03-24 09:11 UTC, Anatolii-Ivanov commented on frontend/src/app/services/comment-reaction.service.ts
> +}
As for me, you build too difficult logic to work with reactions

2022-03-29 12:58 UTC, Jyuart requested changes
We have a pretty large nesting

Video:
- Reactions
- Comments:
  - CommentReactions
  
And there is a problem (slightly visible refresh of the page) when just a single reaction was added to the comment.
To fix this we need not just update the video each time it requires updating, but react correspondingly. For example, after adding new reaction, we make a request to get the full video information, but update just that part that actually changed (like reactions, comments or comments reactions)

2022-03-29 12:58 UTC, Jyuart commented on package.json
> +{
Remove

2022-03-29 12:58 UTC, Jyuart commented on package-lock.json
> +{
Remove

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.API/Controllers/VideoController.cs
> +        public async Task<IActionResult> DeleteReaction(int videoId, Reaction reaction)
I suppose it's not used anymore

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.API/Controllers/CommentController.cs
> +            return Ok(await _commentService.CreateComment(comment));
Do you really need to return it on post?

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.BLL/Services/CommentService.cs
> +            var commentEntity = await _context.Comments.FirstOrDefaultAsync(p => p.Id == commentId);
You still need to fix it. User shouldn't be able to delete comments of other users

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.BLL/Services/CommentService.cs
> +            return _mapper.Map<CommentDTO>(createdComment);
Is it possible to map from `NewCommentDTO` without retrieving it from the db?

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.BLL/Services/VideoService.cs
> +            video.Reactions = _mapper.Map<List<VideoReaction>>(newVideo.Reactions);
Is it possible that video will be created already with some comments?

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.Common/Recodo.Common.csproj
> +    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.13">
Not sure it's needed here

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.DAL/Context/RecodoDbContext.cs
> +        public DbSet<CommentReaction> CommentReactions { get; set; }
No. It's configured as an owned entity of the `Comment`

2022-03-29 12:58 UTC, Jyuart commented on backend/Recodo.DAL/Entities/Comment.cs
> +        public Video Video { get; set; }
Why do you need it?

2022-03-29 12:58 UTC, Jyuart commented on frontend/src/app/modules/workspace/video/comment-reactions/comment-reactions.component.ts
> +  public currentUser: UserDto;
It'd be nice to pass just the user id, not the whole object

2022-03-29 12:58 UTC, Jyuart commented on frontend/src/app/modules/workspace/video/video-page/video-page.component.ts
> +  }
```suggestion
```

2022-03-29 12:58 UTC, Jyuart commented on frontend/src/app/modules/workspace/video/video-page/video-page.component.html
> +  <div *ngIf="isCurrentVideo()">
```suggestion
  <div *ngIf="currentVideo && currentUser">
```

2022-03-29 12:58 UTC, Jyuart commented on frontend/src/app/modules/workspace/video/video-page/video-page.component.html
> +  <div *ngIf="isCurrentVideo()">
But this won't work until you add getting of the current user in this component.
See, you have this property here and pass it to the child, but never initialize. 
Missing `currentUser` is a reason for that missing `avatarLink` error

2022-03-29 12:58 UTC, Jyuart commented on frontend/src/app/modules/workspace/video/video-page/video-page.component.ts
> +          console.log(resp.body);
Remove

2022-03-29 16:22 UTC, shmato4ek commented on backend/Recodo.BLL/Services/CommentService.cs
> +            return _mapper.Map<CommentDTO>(createdComment);
I tried, but it didn`t work without it

2022-03-29 16:23 UTC, shmato4ek commented on backend/Recodo.DAL/Context/RecodoDbContext.cs
> +        public DbSet<CommentReaction> CommentReactions { get; set; }
Yes, but if i delete this line, it will not work, don`t know why

2022-03-31 07:55 UTC, merged